[package]
name = "asm-paint-rs"
version = "0.1.0"
authors = ["Dennis Kobert <d-kobert@web.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = {version="0.3.22", features=["Window", "Document", "HtmlElement", "Node", "Element"]}
