[package]
name = "game-server"
version = "0.1.0"
authors = ["natrixaeria", "truedoctor"]
edition = "2018"
description = "A general game server for connections to web clients. Currently (on the way to) deploying a skribbl.io like game."

[dependencies]
log = "0.4"
fern = "0.5.8"
colored = "1.8"
reqwest = "0.9"
websocket = "0.22"
hyper = "0.10"
